# Generated by Django 4.1.6 on 2023-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
