# Generated by Django 4.1.6 on 2023-02-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_music_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChooseMusicByCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.category",
                    ),
                ),
            ],
        ),
    ]
