# Generated by Django 4.1.6 on 2023-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
