# Generated by Django 4.1.6 on 2023-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_choosemusicbycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
