# Generated by Django 4.1.6 on 2023-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0011_alter_music_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="music_file",
            field=models.FileField(
                blank=True, null=True, upload_to="music/", verbose_name="music file"
            ),
        ),
    ]
