# Generated by Django 4.1.6 on 2023-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_music_music_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس آی پی')),
            ],
            options={
                'verbose_name': 'آدرس آی پی',
                'verbose_name_plural': 'آدرس های آی پی',
            },
        ),
    ]
