# Generated by Django 4.1.6 on 2023-12-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_music_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='music_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.music'),
        ),
    ]
