# Generated by Django 4.1.6 on 2023-03-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'پلی لیست', 'verbose_name_plural': 'پلی لیست ها'},
        ),
    ]
