# Generated by Django 4.1.6 on 2023-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_music_title'),
        ('play_list', '0002_alter_playlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music.music', verbose_name='songs'),
        ),
    ]
