# Generated by Django 4.1.6 on 2023-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_list', '0004_playlist_approved_playlist_alter_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_international',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
