# Generated by Django 4.1.6 on 2023-04-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ticket_delete_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsTitle',
            new_name='TicketTitle',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت'},
        ),
        migrations.AlterModelOptions(
            name='tickettitle',
            options={'verbose_name': 'عنوان تیکت', 'verbose_name_plural': 'عنواین تیکت'},
        ),
    ]
