# Generated by Django 4.1.6 on 2024-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_update', models.BooleanField(blank=True, default=False, null=True)),
                ('is_update_required', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
